spring:
  application:
    name: microservice-products
  datasource:
    url: jdbc:postgresql://localhost:5432/db-develop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080